[package]
name = "HiC-Dip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
hdf5 = "0.8.1"
polars = { version = "0.39", features = ["lazy", "ndarray", "dtype-struct","csv"] }
ndarray = "0.15"
rand = "0.8"
